baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Andrew's Homelab Chronicles"
theme = 'hugo-book'

[params]
  BookSection = '*'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
